# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custommodel',
            managers=[
            ],
        ),
    ]
