# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190327_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommodel',
            name='phone_number',
        ),
    ]
