# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_custommodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=243, null=True, verbose_name='phone_number'),
        ),
    ]
